import React, { createContext, useCallback, useContext, useEffect, useState } from "react";
import * as SecureStore from "expo-secure-store";
import { I18nManager, Platform } from "react-native";

export type Lang = "en" | "fr" | "ar";

export const LANGS: { code: Lang; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "fr", label: "French", native: "Français" },
  { code: "ar", label: "Arabic", native: "العربية" },
];

const STORAGE_KEY = "sp_lang";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const dict: Record<Lang, Record<string, string>> = {
  en: {
    // Brand
    "app.name": "khedmaPro",
    // Onboarding
    "onboarding.title": "Trusted pros\nat your fingertips.",
    "onboarding.subtitle": "Browse vetted service providers instantly — no account needed to search or book.",
    "onboarding.browse": "Browse services",
    "onboarding.iamProvider": "I'm a service provider",
    "onboarding.haveAccount": "Have a provider account?",
    "onboarding.signIn": "Sign in",
    // Home
    "home.helloGuest": "Find a pro",
    "home.hello": "Hello",
    "home.searchPlaceholder": "Search providers, services...",
    "home.promoBadge": "NEW",
    "home.promoTitle": "Book vetted pros\nacross Algeria",
    "home.promoSub": "Trusted service providers, transparent pricing.",
    "home.categories": "Categories",
    "home.all": "All",
    "home.topRated": "Top rated",
    "home.allProviders": "All providers",
    "home.noResults": "No providers found",
    "home.headerSignIn": "Sign in",
    // Categories
    "cat.plumbing": "Plumbing",
    "cat.electrical": "Electrical",
    "cat.cleaning": "Cleaning",
    "cat.carpentry": "Carpentry",
    "cat.painting": "Painting",
    "cat.landscaping": "Landscaping",
    "cat.it_support": "IT Support",
    "cat.admin_education": "Admin Education",
    "cat.photography": "Photography",
    "cat.moving": "Moving",
    // Provider detail
    "provider.verified": "Verified",
    "provider.reviews": "Reviews",
    "provider.noReviews": "No reviews yet. Be the first!",
    "provider.perHour": "DZD / hour",
    "provider.perTask": "DZD / task",
    "provider.requestBooking": "Request Booking",
    "provider.writeReview": "Write a review",
    // Booking
    "booking.title": "Request booking",
    "booking.selectDate": "Select date",
    "booking.selectTime": "Select time",
    "booking.rateType": "Rate type",
    "booking.hourly": "Hourly",
    "booking.task": "Task",
    "booking.hours": "Estimated hours",
    "booking.description": "Task description",
    "booking.descriptionPh": "Describe what you need done...",
    "booking.address": "Address",
    "booking.addressPh": "Street, city",
    "booking.yourInfo": "Your contact info",
    "booking.name": "Full name",
    "booking.phone": "Phone",
    "booking.email": "Email (optional)",
    "booking.total": "Estimated total",
    "booking.confirm": "Confirm",
    "booking.success": "Booking requested!",
    "booking.successSub": "will respond shortly.",
    "booking.viewBookings": "View bookings",
    "booking.done": "Done",
    "booking.errFill": "Please add task description and address",
    "booking.errGuest": "Please enter your name and phone",
    // Bookings tab
    "bookings.title": "My bookings",
    "bookings.all": "All",
    "bookings.pending": "Pending",
    "bookings.confirmed": "Confirmed",
    "bookings.completed": "Completed",
    "bookings.empty": "No bookings yet",
    "bookings.accept": "Accept",
    "bookings.decline": "Decline",
    "bookings.markComplete": "Mark complete",
    "bookings.cancel": "Cancel",
    "bookings.leaveReview": "Leave review",
    // Auth
    "auth.welcomeBack": "Welcome back",
    "auth.signInSub": "Sign in to your khedmaPro account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signInBtn": "Sign in",
    "auth.noAccount": "Don't have an account?",
    "auth.signUp": "Sign up",
    "auth.createAccount": "Create account",
    "auth.joinSub": "Join khedmaPro today",
    "auth.client": "Client",
    "auth.provider": "Provider",
    "auth.fullName": "Full name",
    "auth.phoneOptional": "Phone (optional)",
    "auth.cityOptional": "City (optional)",
    "auth.category": "Service category",
    "auth.bio": "Bio",
    "auth.bioPh": "Tell clients about your experience",
    "auth.hourlyRate": "Hourly rate (DZD)",
    "auth.taskRate": "Task rate (DZD)",
    "auth.trial": "3 months free, then 1000 DZD/month to stay listed.",
    "auth.createBtn": "Create account",
    "auth.haveAccount": "Already have an account?",
    "auth.errFill": "Please fill required fields",
    "auth.errCategory": "Please select a service category",
    // Review
    "review.title": "Leave a review",
    "review.prompt": "How was your experience?",
    "review.commentPh": "Tell others about your experience...",
    "review.submit": "Submit review",
    "review.needAccount": "Sign in required",
    "review.needAccountSub": "Create a free client account to leave a review.",
    // Profile
    "profile.title": "Profile",
    "profile.phone": "Phone",
    "profile.city": "City",
    "profile.signOut": "Sign out",
    "profile.guestTitle": "Sign in to unlock more",
    "profile.guestSub": "Create a free client account to track your bookings and leave reviews for the pros you hire.",
    "profile.guestCreate": "Create client account",
    "profile.guestSignIn": "Sign in",
    "profile.language": "Language",
    // Provider dashboard
    "dash.subDesc": "Here's how your business looks today.",
    "dash.subActive": "Subscription active",
    "dash.subTrial": "Free trial active",
    "dash.subDue": "Payment required",
    "dash.subDeact": "Profile deactivated",
    "dash.subActiveSub": "Renews in {days} days.",
    "dash.subTrialSub": "{days} days remaining. Then 1000 DZD/month.",
    "dash.subDueSub": "Pay 1000 DZD to keep your profile listed.",
    "dash.subDeactSub": "Contact support to reactivate.",
    "dash.pay": "Pay 1000 DZD",
    "dash.renew": "Renew now",
    "dash.earned": "DZD earned",
    "dash.completed": "Completed",
    "dash.upcoming": "Upcoming",
    "dash.pending": "Pending",
    "dash.yourRating": "Your rating",
    "dash.reviews": "reviews",
    "dash.recent": "Recent bookings",
    "dash.noBookings": "No bookings yet",
    "dash.noBookingsSub": "Clients will see your profile in the marketplace.",
    // Chat
    "chat.title": "Messages",
    "chat.empty": "No conversations yet",
    "chat.emptySub": "Start a chat from a provider profile.",
    "chat.placeholder": "Type a message…",
    "chat.send": "Send",
    "chat.safety": "Discuss job details safely — no phone numbers needed.",
    "chat.messageBtn": "Message",
    // Schedule
    "schedule.title": "My schedule",
    "schedule.workingHours": "Working hours",
    "schedule.breaks": "Breaks",
    "schedule.vacation": "Vacation days",
    "schedule.save": "Save schedule",
    "schedule.saved": "Schedule saved",
    "schedule.offlineHint": "Offline · showing cached data",
    "schedule.closed": "Closed",
    "schedule.setHours": "Set hours",
    "schedule.start": "Start",
    "schedule.end": "End",
    "schedule.tapDay": "Tap a day to add/remove a vacation",
    "schedule.langRestart": "Language applied. Restart the app for full RTL layout.",
    // Address
    "address.suggestions": "Suggestions",
    "address.searching": "Searching…",
    // Days
    "day.mon": "Monday",
    "day.tue": "Tuesday",
    "day.wed": "Wednesday",
    "day.thu": "Thursday",
    "day.fri": "Friday",
    "day.sat": "Saturday",
    "day.sun": "Sunday",
    // OTP
    "otp.title": "Continue with phone",
    "otp.subtitle": "We'll send you a 6-digit verification code.",
    "otp.phone": "Phone number",
    "otp.sendCode": "Send code",
    "otp.enterCode": "Enter the 6-digit code sent to",
    "otp.code": "Verification code",
    "otp.verify": "Verify",
    "otp.resend": "Resend code",
    "otp.resendIn": "Resend in {sec}s",
    "otp.wrongNumber": "Wrong number?",
    "otp.mockHint": "MOCK MODE — check the backend logs for the code.",
    "otp.iAm": "I am a",
    "otp.roleClient": "Client",
    "otp.roleProvider": "Service provider",
    "otp.errPhone": "Please enter a valid Algerian mobile number",
    "otp.errCode": "Please enter the 6-digit code",
    // Profile completion
    "profileC.title": "Complete your profile",
    "profileC.sub": "A few last details before we get started.",
    "profileC.save": "Save and continue",
    // Auth options
    "auth.orPhone": "or continue with phone",
    // Wilaya / location
    "wilaya.select": "Select wilaya",
    "wilaya.searchPh": "Search 58 wilayas…",
    "wilaya.mine": "My wilaya",
    "wilaya.crossOn": "Available across wilayas",
    "wilaya.crossOff": "Only my wilaya",
    "wilaya.baladiya": "Baladiya (municipality)",
    "wilaya.baladiyaPh": "e.g. Bab Ezzouar",
    "wilaya.filterAll": "All Algeria",
    // Booking type
    "booking.instant": "Instant booking",
    "booking.instantSub": "Book now at listed rate",
    "booking.quote": "Request quote",
    "booking.quoteSub": "Complex job — get a custom price",
    "booking.pinTitle": "Drop a pin at the service location",
    "booking.pinHint": "Tap the map or drag the marker to precisely mark the location.",
    "booking.pinConfirm": "Confirm location",
    "booking.locationSet": "Location pinned",
    // Report
    "report.title": "Report provider",
    "report.reason": "Reason",
    "report.details": "Details (optional)",
    "report.detailsPh": "Tell us what happened…",
    "report.submit": "Submit report",
    "report.submitted": "Report submitted. Thank you.",
    "report.reasons.noShow": "No-show / did not deliver",
    "report.reasons.poorQuality": "Poor quality",
    "report.reasons.priceGouging": "Overcharged",
    "report.reasons.unsafe": "Unsafe behavior",
    "report.reasons.fraud": "Fraud / scam",
    "report.reasons.other": "Other",
    "report.needAccount": "Sign in required to report",
    // Portfolio
    "portfolio.title": "Portfolio",
    "portfolio.empty": "No photos yet",
    "portfolio.add": "Add photo",
    "portfolio.compressing": "Compressing…",
    "portfolio.limit": "Up to 12 photos",
    "common.retry": "Retry",
  },
  fr: {
    "app.name": "khedmaPro",
    "onboarding.title": "Des pros de confiance\nà portée de main.",
    "onboarding.subtitle": "Parcourez des prestataires vérifiés instantanément — pas besoin de compte pour chercher ou réserver.",
    "onboarding.browse": "Parcourir les services",
    "onboarding.iamProvider": "Je suis un prestataire",
    "onboarding.haveAccount": "Vous avez un compte prestataire ?",
    "onboarding.signIn": "Se connecter",
    "home.helloGuest": "Trouver un pro",
    "home.hello": "Bonjour",
    "home.searchPlaceholder": "Rechercher un prestataire, un service...",
    "home.promoBadge": "NOUVEAU",
    "home.promoTitle": "Réservez des pros vérifiés\ndans toute l'Algérie",
    "home.promoSub": "Prestataires de confiance, tarifs transparents.",
    "home.categories": "Catégories",
    "home.all": "Tous",
    "home.topRated": "Les mieux notés",
    "home.allProviders": "Tous les prestataires",
    "home.noResults": "Aucun prestataire trouvé",
    "home.headerSignIn": "Se connecter",
    "cat.plumbing": "Plomberie",
    "cat.electrical": "Électricité",
    "cat.cleaning": "Nettoyage",
    "cat.carpentry": "Menuiserie",
    "cat.painting": "Peinture",
    "cat.landscaping": "Jardinage",
    "cat.it_support": "Support IT",
    "cat.admin_education": "Aide administrative",
    "cat.photography": "Photographie",
    "cat.moving": "Déménagement",
    "provider.verified": "Vérifié",
    "provider.reviews": "Avis",
    "provider.noReviews": "Aucun avis pour l'instant. Soyez le premier !",
    "provider.perHour": "DZD / heure",
    "provider.perTask": "DZD / tâche",
    "provider.requestBooking": "Demander une réservation",
    "provider.writeReview": "Laisser un avis",
    "booking.title": "Demander une réservation",
    "booking.selectDate": "Choisir la date",
    "booking.selectTime": "Choisir l'heure",
    "booking.rateType": "Type de tarif",
    "booking.hourly": "Horaire",
    "booking.task": "Tâche",
    "booking.hours": "Heures estimées",
    "booking.description": "Description de la tâche",
    "booking.descriptionPh": "Décrivez ce que vous avez besoin...",
    "booking.address": "Adresse",
    "booking.addressPh": "Rue, ville",
    "booking.yourInfo": "Vos coordonnées",
    "booking.name": "Nom complet",
    "booking.phone": "Téléphone",
    "booking.email": "Email (optionnel)",
    "booking.total": "Total estimé",
    "booking.confirm": "Confirmer",
    "booking.success": "Réservation envoyée !",
    "booking.successSub": "répondra bientôt.",
    "booking.viewBookings": "Voir mes réservations",
    "booking.done": "Terminé",
    "booking.errFill": "Veuillez ajouter la description et l'adresse",
    "booking.errGuest": "Veuillez saisir votre nom et téléphone",
    "bookings.title": "Mes réservations",
    "bookings.all": "Toutes",
    "bookings.pending": "En attente",
    "bookings.confirmed": "Confirmées",
    "bookings.completed": "Terminées",
    "bookings.empty": "Aucune réservation",
    "bookings.accept": "Accepter",
    "bookings.decline": "Refuser",
    "bookings.markComplete": "Marquer terminée",
    "bookings.cancel": "Annuler",
    "bookings.leaveReview": "Laisser un avis",
    "auth.welcomeBack": "Bon retour",
    "auth.signInSub": "Connectez-vous à votre compte khedmaPro",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.signInBtn": "Se connecter",
    "auth.noAccount": "Pas de compte ?",
    "auth.signUp": "S'inscrire",
    "auth.createAccount": "Créer un compte",
    "auth.joinSub": "Rejoignez khedmaPro aujourd'hui",
    "auth.client": "Client",
    "auth.provider": "Prestataire",
    "auth.fullName": "Nom complet",
    "auth.phoneOptional": "Téléphone (optionnel)",
    "auth.cityOptional": "Ville (optionnel)",
    "auth.category": "Catégorie de service",
    "auth.bio": "Bio",
    "auth.bioPh": "Parlez aux clients de votre expérience",
    "auth.hourlyRate": "Tarif horaire (DZD)",
    "auth.taskRate": "Tarif à la tâche (DZD)",
    "auth.trial": "3 mois gratuits, puis 1000 DZD/mois pour rester listé.",
    "auth.createBtn": "Créer un compte",
    "auth.haveAccount": "Vous avez déjà un compte ?",
    "auth.errFill": "Veuillez remplir les champs requis",
    "auth.errCategory": "Veuillez choisir une catégorie",
    "review.title": "Laisser un avis",
    "review.prompt": "Comment était votre expérience ?",
    "review.commentPh": "Partagez votre expérience...",
    "review.submit": "Envoyer l'avis",
    "review.needAccount": "Connexion requise",
    "review.needAccountSub": "Créez un compte client gratuit pour laisser un avis.",
    "profile.title": "Profil",
    "profile.phone": "Téléphone",
    "profile.city": "Ville",
    "profile.signOut": "Se déconnecter",
    "profile.guestTitle": "Connectez-vous pour plus",
    "profile.guestSub": "Créez un compte client gratuit pour suivre vos réservations et laisser des avis.",
    "profile.guestCreate": "Créer un compte client",
    "profile.guestSignIn": "Se connecter",
    "profile.language": "Langue",
    "dash.subDesc": "Voici votre activité aujourd'hui.",
    "dash.subActive": "Abonnement actif",
    "dash.subTrial": "Essai gratuit actif",
    "dash.subDue": "Paiement requis",
    "dash.subDeact": "Profil désactivé",
    "dash.subActiveSub": "Renouvellement dans {days} jours.",
    "dash.subTrialSub": "{days} jours restants. Ensuite 1000 DZD/mois.",
    "dash.subDueSub": "Payez 1000 DZD pour rester listé.",
    "dash.subDeactSub": "Contactez le support pour réactiver.",
    "dash.pay": "Payer 1000 DZD",
    "dash.renew": "Renouveler",
    "dash.earned": "DZD gagnés",
    "dash.completed": "Terminées",
    "dash.upcoming": "À venir",
    "dash.pending": "En attente",
    "dash.yourRating": "Votre note",
    "dash.reviews": "avis",
    "dash.recent": "Réservations récentes",
    "dash.noBookings": "Aucune réservation",
    "dash.noBookingsSub": "Les clients verront votre profil dans la marketplace.",
    "chat.title": "Messages",
    "chat.empty": "Aucune conversation",
    "chat.emptySub": "Commencez une discussion depuis un profil de prestataire.",
    "chat.placeholder": "Écrire un message…",
    "chat.send": "Envoyer",
    "chat.safety": "Discutez en toute sécurité — pas besoin de numéro personnel.",
    "chat.messageBtn": "Message",
    "schedule.title": "Mon planning",
    "schedule.workingHours": "Heures d'ouverture",
    "schedule.breaks": "Pauses",
    "schedule.vacation": "Jours de congé",
    "schedule.save": "Enregistrer",
    "schedule.saved": "Planning enregistré",
    "schedule.offlineHint": "Hors ligne · données en cache",
    "schedule.closed": "Fermé",
    "schedule.setHours": "Définir",
    "schedule.start": "Début",
    "schedule.end": "Fin",
    "schedule.tapDay": "Touchez un jour pour ajouter/retirer un congé",
    "schedule.langRestart": "Langue appliquée. Redémarrez l'app pour le RTL complet.",
    "address.suggestions": "Suggestions",
    "address.searching": "Recherche…",
    "day.mon": "Lundi",
    "day.tue": "Mardi",
    "day.wed": "Mercredi",
    "day.thu": "Jeudi",
    "day.fri": "Vendredi",
    "day.sat": "Samedi",
    "day.sun": "Dimanche",
    "otp.title": "Continuer avec votre téléphone",
    "otp.subtitle": "Nous vous enverrons un code à 6 chiffres.",
    "otp.phone": "Numéro de téléphone",
    "otp.sendCode": "Envoyer le code",
    "otp.enterCode": "Entrez le code à 6 chiffres envoyé à",
    "otp.code": "Code de vérification",
    "otp.verify": "Vérifier",
    "otp.resend": "Renvoyer",
    "otp.resendIn": "Renvoyer dans {sec}s",
    "otp.wrongNumber": "Mauvais numéro ?",
    "otp.mockHint": "MODE TEST — consultez les logs du backend pour le code.",
    "otp.iAm": "Je suis un",
    "otp.roleClient": "Client",
    "otp.roleProvider": "Prestataire",
    "otp.errPhone": "Numéro algérien invalide",
    "otp.errCode": "Entrez le code à 6 chiffres",
    "profileC.title": "Complétez votre profil",
    "profileC.sub": "Quelques derniers détails avant de commencer.",
    "profileC.save": "Enregistrer et continuer",
    "auth.orPhone": "ou continuer avec votre téléphone",
    "wilaya.select": "Choisir la wilaya",
    "wilaya.searchPh": "Rechercher parmi 58 wilayas…",
    "wilaya.mine": "Ma wilaya",
    "wilaya.crossOn": "Disponible dans toutes les wilayas",
    "wilaya.crossOff": "Uniquement ma wilaya",
    "wilaya.baladiya": "Baladiya (commune)",
    "wilaya.baladiyaPh": "ex. Bab Ezzouar",
    "wilaya.filterAll": "Toute l'Algérie",
    "booking.instant": "Réservation instantanée",
    "booking.instantSub": "Au tarif affiché",
    "booking.quote": "Demander un devis",
    "booking.quoteSub": "Travail complexe — prix sur mesure",
    "booking.pinTitle": "Placez une épingle à l'emplacement",
    "booking.pinHint": "Touchez la carte ou déplacez le marqueur pour indiquer précisément le lieu.",
    "booking.pinConfirm": "Confirmer l'emplacement",
    "booking.locationSet": "Lieu épinglé",
    "report.title": "Signaler ce prestataire",
    "report.reason": "Motif",
    "report.details": "Détails (optionnel)",
    "report.detailsPh": "Dites-nous ce qui s'est passé…",
    "report.submit": "Envoyer le signalement",
    "report.submitted": "Signalement envoyé. Merci.",
    "report.reasons.noShow": "Absent / non-livraison",
    "report.reasons.poorQuality": "Mauvaise qualité",
    "report.reasons.priceGouging": "Facturation excessive",
    "report.reasons.unsafe": "Comportement dangereux",
    "report.reasons.fraud": "Fraude / arnaque",
    "report.reasons.other": "Autre",
    "report.needAccount": "Connexion requise pour signaler",
    "portfolio.title": "Portfolio",
    "portfolio.empty": "Aucune photo",
    "portfolio.add": "Ajouter",
    "portfolio.compressing": "Compression…",
    "portfolio.limit": "Jusqu'à 12 photos",
    "common.retry": "Réessayer",
  },
  ar: {
    "app.name": "خدمة برو",
    "onboarding.title": "محترفون موثوقون\nفي متناول يدك.",
    "onboarding.subtitle": "تصفح مقدمي الخدمات المعتمدين فورًا — لا حاجة لإنشاء حساب للبحث أو الحجز.",
    "onboarding.browse": "تصفح الخدمات",
    "onboarding.iamProvider": "أنا مقدم خدمة",
    "onboarding.haveAccount": "لديك حساب مقدم خدمة؟",
    "onboarding.signIn": "تسجيل الدخول",
    "home.helloGuest": "ابحث عن محترف",
    "home.hello": "مرحبًا",
    "home.searchPlaceholder": "ابحث عن مقدم خدمة أو خدمة...",
    "home.promoBadge": "جديد",
    "home.promoTitle": "احجز محترفين موثوقين\nفي جميع أنحاء الجزائر",
    "home.promoSub": "مقدمو خدمات موثوقون بأسعار شفافة.",
    "home.categories": "الفئات",
    "home.all": "الكل",
    "home.topRated": "الأعلى تقييمًا",
    "home.allProviders": "جميع مقدمي الخدمات",
    "home.noResults": "لا يوجد مقدمو خدمات",
    "home.headerSignIn": "دخول",
    "cat.plumbing": "سباكة",
    "cat.electrical": "كهرباء",
    "cat.cleaning": "تنظيف",
    "cat.carpentry": "نجارة",
    "cat.painting": "دهان",
    "cat.landscaping": "بستنة",
    "cat.it_support": "دعم تقني",
    "cat.admin_education": "دعم إداري وتعليمي",
    "cat.photography": "تصوير",
    "cat.moving": "نقل الأثاث",
    "provider.verified": "موثوق",
    "provider.reviews": "التقييمات",
    "provider.noReviews": "لا توجد تقييمات بعد. كن الأول!",
    "provider.perHour": "دج / ساعة",
    "provider.perTask": "دج / مهمة",
    "provider.requestBooking": "طلب حجز",
    "provider.writeReview": "اكتب تقييمًا",
    "booking.title": "طلب حجز",
    "booking.selectDate": "اختر التاريخ",
    "booking.selectTime": "اختر الوقت",
    "booking.rateType": "نوع التسعير",
    "booking.hourly": "بالساعة",
    "booking.task": "بالمهمة",
    "booking.hours": "الساعات المقدرة",
    "booking.description": "وصف المهمة",
    "booking.descriptionPh": "صف ما تحتاج القيام به...",
    "booking.address": "العنوان",
    "booking.addressPh": "الشارع، المدينة",
    "booking.yourInfo": "بيانات التواصل",
    "booking.name": "الاسم الكامل",
    "booking.phone": "الهاتف",
    "booking.email": "البريد الإلكتروني (اختياري)",
    "booking.total": "الإجمالي المقدر",
    "booking.confirm": "تأكيد",
    "booking.success": "تم إرسال الطلب!",
    "booking.successSub": "سيرد عليك قريبًا.",
    "booking.viewBookings": "عرض الحجوزات",
    "booking.done": "تم",
    "booking.errFill": "يرجى إضافة وصف المهمة والعنوان",
    "booking.errGuest": "يرجى إدخال اسمك ورقم هاتفك",
    "bookings.title": "حجوزاتي",
    "bookings.all": "الكل",
    "bookings.pending": "قيد الانتظار",
    "bookings.confirmed": "مؤكدة",
    "bookings.completed": "منجزة",
    "bookings.empty": "لا توجد حجوزات",
    "bookings.accept": "قبول",
    "bookings.decline": "رفض",
    "bookings.markComplete": "تحديد كمنجز",
    "bookings.cancel": "إلغاء",
    "bookings.leaveReview": "اكتب تقييمًا",
    "auth.welcomeBack": "مرحبًا بعودتك",
    "auth.signInSub": "سجّل الدخول إلى حسابك في خدمة برو",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.signInBtn": "تسجيل الدخول",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.signUp": "أنشئ حسابًا",
    "auth.createAccount": "إنشاء حساب",
    "auth.joinSub": "انضم إلى خدمة برو اليوم",
    "auth.client": "عميل",
    "auth.provider": "مقدم خدمة",
    "auth.fullName": "الاسم الكامل",
    "auth.phoneOptional": "الهاتف (اختياري)",
    "auth.cityOptional": "المدينة (اختياري)",
    "auth.category": "فئة الخدمة",
    "auth.bio": "نبذة",
    "auth.bioPh": "أخبر العملاء عن خبرتك",
    "auth.hourlyRate": "التعرفة بالساعة (دج)",
    "auth.taskRate": "التعرفة بالمهمة (دج)",
    "auth.trial": "3 أشهر مجانًا، ثم 1000 دج/شهر للبقاء مدرجًا.",
    "auth.createBtn": "إنشاء الحساب",
    "auth.haveAccount": "لديك حساب بالفعل؟",
    "auth.errFill": "يرجى ملء الحقول المطلوبة",
    "auth.errCategory": "يرجى اختيار فئة",
    "review.title": "اكتب تقييمًا",
    "review.prompt": "كيف كانت تجربتك؟",
    "review.commentPh": "شارك تجربتك مع الآخرين...",
    "review.submit": "إرسال التقييم",
    "review.needAccount": "تسجيل الدخول مطلوب",
    "review.needAccountSub": "أنشئ حساب عميل مجاني لكتابة تقييم.",
    "profile.title": "الملف الشخصي",
    "profile.phone": "الهاتف",
    "profile.city": "المدينة",
    "profile.signOut": "تسجيل الخروج",
    "profile.guestTitle": "سجّل الدخول للمزيد",
    "profile.guestSub": "أنشئ حساب عميل مجاني لتتبع حجوزاتك وترك التقييمات.",
    "profile.guestCreate": "إنشاء حساب عميل",
    "profile.guestSignIn": "تسجيل الدخول",
    "profile.language": "اللغة",
    "dash.subDesc": "هذه نظرة على نشاطك اليوم.",
    "dash.subActive": "الاشتراك نشط",
    "dash.subTrial": "الفترة التجريبية نشطة",
    "dash.subDue": "الدفع مطلوب",
    "dash.subDeact": "الملف الشخصي معطل",
    "dash.subActiveSub": "يتجدد خلال {days} يومًا.",
    "dash.subTrialSub": "متبقٍ {days} يومًا. ثم 1000 دج/شهر.",
    "dash.subDueSub": "ادفع 1000 دج لإبقاء ملفك مدرجًا.",
    "dash.subDeactSub": "تواصل مع الدعم لإعادة التفعيل.",
    "dash.pay": "ادفع 1000 دج",
    "dash.renew": "تجديد الآن",
    "dash.earned": "دج مكتسبة",
    "dash.completed": "منجزة",
    "dash.upcoming": "قادمة",
    "dash.pending": "قيد الانتظار",
    "dash.yourRating": "تقييمك",
    "dash.reviews": "تقييم",
    "dash.recent": "الحجوزات الأخيرة",
    "dash.noBookings": "لا توجد حجوزات",
    "dash.noBookingsSub": "سيرى العملاء ملفك في السوق.",
    "chat.title": "الرسائل",
    "chat.empty": "لا توجد محادثات",
    "chat.emptySub": "ابدأ محادثة من ملف مقدم الخدمة.",
    "chat.placeholder": "اكتب رسالة…",
    "chat.send": "إرسال",
    "chat.safety": "تحدث بأمان — دون الحاجة لمشاركة رقم هاتفك.",
    "chat.messageBtn": "مراسلة",
    "schedule.title": "جدولي",
    "schedule.workingHours": "ساعات العمل",
    "schedule.breaks": "الاستراحات",
    "schedule.vacation": "أيام الإجازة",
    "schedule.save": "حفظ",
    "schedule.saved": "تم حفظ الجدول",
    "schedule.offlineHint": "غير متصل · بيانات مخبأة",
    "schedule.closed": "مغلق",
    "schedule.setHours": "تحديد",
    "schedule.start": "البداية",
    "schedule.end": "النهاية",
    "schedule.tapDay": "اضغط على يوم لإضافة/إزالة إجازة",
    "schedule.langRestart": "تم تطبيق اللغة. أعد تشغيل التطبيق لتفعيل RTL بالكامل.",
    "address.suggestions": "اقتراحات",
    "address.searching": "بحث…",
    "day.mon": "الاثنين",
    "day.tue": "الثلاثاء",
    "day.wed": "الأربعاء",
    "day.thu": "الخميس",
    "day.fri": "الجمعة",
    "day.sat": "السبت",
    "day.sun": "الأحد",
    "otp.title": "المتابعة برقم الهاتف",
    "otp.subtitle": "سنرسل لك رمز التحقق المكون من 6 أرقام.",
    "otp.phone": "رقم الهاتف",
    "otp.sendCode": "إرسال الرمز",
    "otp.enterCode": "أدخل الرمز المرسل إلى",
    "otp.code": "رمز التحقق",
    "otp.verify": "تحقق",
    "otp.resend": "إعادة الإرسال",
    "otp.resendIn": "إعادة الإرسال خلال {sec} ثانية",
    "otp.wrongNumber": "رقم خاطئ؟",
    "otp.mockHint": "وضع تجريبي — تحقق من سجلات الخادم للحصول على الرمز.",
    "otp.iAm": "أنا",
    "otp.roleClient": "عميل",
    "otp.roleProvider": "مقدم خدمة",
    "otp.errPhone": "رقم جزائري غير صالح",
    "otp.errCode": "أدخل الرمز المكون من 6 أرقام",
    "profileC.title": "أكمل ملفك الشخصي",
    "profileC.sub": "بعض التفاصيل الأخيرة قبل البدء.",
    "profileC.save": "حفظ ومتابعة",
    "auth.orPhone": "أو المتابعة برقم الهاتف",
    "wilaya.select": "اختر الولاية",
    "wilaya.searchPh": "ابحث ضمن 58 ولاية…",
    "wilaya.mine": "ولايتي",
    "wilaya.crossOn": "متوفر في جميع الولايات",
    "wilaya.crossOff": "ولايتي فقط",
    "wilaya.baladiya": "البلدية",
    "wilaya.baladiyaPh": "مثل: باب الزوار",
    "wilaya.filterAll": "كل الجزائر",
    "booking.instant": "حجز فوري",
    "booking.instantSub": "بالتسعيرة المعلنة",
    "booking.quote": "طلب عرض سعر",
    "booking.quoteSub": "عمل معقد — سعر مخصص",
    "booking.pinTitle": "ضع دبوسًا على موقع الخدمة",
    "booking.pinHint": "اضغط على الخريطة أو اسحب الدبوس لتحديد الموقع بدقة.",
    "booking.pinConfirm": "تأكيد الموقع",
    "booking.locationSet": "تم تحديد الموقع",
    "report.title": "الإبلاغ عن مقدم الخدمة",
    "report.reason": "السبب",
    "report.details": "التفاصيل (اختياري)",
    "report.detailsPh": "أخبرنا بما حدث…",
    "report.submit": "إرسال البلاغ",
    "report.submitted": "تم إرسال البلاغ. شكرًا.",
    "report.reasons.noShow": "لم يحضر / لم يقدم الخدمة",
    "report.reasons.poorQuality": "جودة رديئة",
    "report.reasons.priceGouging": "مبالغة في السعر",
    "report.reasons.unsafe": "سلوك غير آمن",
    "report.reasons.fraud": "احتيال",
    "report.reasons.other": "أخرى",
    "report.needAccount": "يجب تسجيل الدخول للإبلاغ",
    "portfolio.title": "أعمالي",
    "portfolio.empty": "لا توجد صور بعد",
    "portfolio.add": "إضافة صورة",
    "portfolio.compressing": "جاري الضغط…",
    "portfolio.limit": "حتى 12 صورة",
    "common.retry": "إعادة المحاولة",
  },
};

type LangCtx = {
  lang: Lang;
  isRTL: boolean;
  setLang: (l: Lang) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
};

const Ctx = createContext<LangCtx | undefined>(undefined);

async function readLang(): Promise<Lang | null> {
  if (Platform.OS === "web") return null;
  try {
    const v = await SecureStore.getItemAsync(STORAGE_KEY);
    if (v === "en" || v === "fr" || v === "ar") return v;
  } catch {}
  return null;
}

async function writeLang(l: Lang) {
  if (Platform.OS === "web") return;
  try {
    await SecureStore.setItemAsync(STORAGE_KEY, l);
  } catch {}
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    (async () => {
      const saved = await readLang();
      if (saved) setLangState(saved);
      // Apply RTL layout when appropriate. On native this requires an app reload
      // to take full effect for flex direction; text-level RTL still works.
      const shouldRTL = (saved || "en") === "ar";
      try {
        if (I18nManager.isRTL !== shouldRTL) {
          I18nManager.allowRTL(shouldRTL);
          I18nManager.forceRTL(shouldRTL);
        }
      } catch {}
    })();
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    writeLang(l);
    // Toggle RTL. Restart needed on native for full effect (user is prompted in UI).
    try {
      const rtl = l === "ar";
      if (I18nManager.isRTL !== rtl) {
        I18nManager.allowRTL(rtl);
        I18nManager.forceRTL(rtl);
      }
    } catch {}
  }, []);

  const t = useCallback(
    (key: string, params?: Record<string, string | number>) => {
      let s = dict[lang][key] || dict.en[key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          s = s.replace(`{${k}}`, String(v));
        });
      }
      return s;
    },
    [lang]
  );

  const value: LangCtx = {
    lang,
    isRTL: lang === "ar",
    setLang,
    t,
  };

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useT() {
  const c = useContext(Ctx);
  if (!c) throw new Error("useT must be used inside LanguageProvider");
  return c;
}
